image: java

stages: 
  - test
  - build
  - analyze

artifacts:
  paths:
    - build/distributions

cache: 
  paths: 
    - .gradle/

unit test:
  stage: test
  script:
    - ./gradlew test

build:
  stage: build
  script:
    - ./gradlew build

sonar:
  stage: analyze
  script:
  - ./gradlew sonarqube -Dsonar.host.url=$$$SONAR_URL$$$ -Dsonar.projectKey=$$$SONAR_PROJECT_KEY$$$ -Dsonar.projectName=$$$SONAR_PROJECT_KEY$$$

